import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "var(--color-surface-bright)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-surface": "var(--color-on-surface)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "inverse-surface": "var(--color-inverse-surface)",
        "tertiary": "var(--color-tertiary)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "primary": "var(--color-primary)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "secondary-container": "var(--color-secondary-container)",
        "outline": "var(--color-outline)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "surface-variant": "var(--color-surface-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "outline-variant": "var(--color-outline-variant)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-secondary": "var(--color-on-secondary)",
        "surface-container-high": "var(--color-surface-container-high)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "error": "var(--color-error)",
        "surface-container": "var(--color-surface-container)",
        "on-background": "var(--color-on-background)",
        "on-error-container": "var(--color-on-error-container)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface": "var(--color-surface)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "secondary": "var(--color-secondary)",
        "on-primary": "var(--color-on-primary)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "surface-container-low": "var(--color-surface-container-low)",
        "background": "var(--color-background)",
        "surface-tint": "var(--color-surface-tint)",
        "primary-fixed": "var(--color-primary-fixed)"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "container-padding": "24px",
        "margin-mobile": "16px",
        "gutter": "16px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "label-caps": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "mono-data": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "price-display": ["Inter"],
        "headline-sm": ["Playfair Display"],
        "body-md": ["Inter"],
        "headline-md": ["Playfair Display"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-caps": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "display-lg-mobile": ["36px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "title-md": ["20px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "mono-data": ["14px", { "lineHeight": "1.0", "letterSpacing": "0.02em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "price-display": ["20px", { lineHeight: "24px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      }
    }
  },
  plugins: [
    forms,
    containerQueries
  ],
}
