export const PAYMENT_TYPE = {
  CASH: 'CASH',
  RAZORPAY: 'RAZORPAY',
  CARD: 'CARD',
  UPI: 'UPI',
  ONLINE: 'ONLINE',
  LATER: 'LATER'
};

export const ADMIN_SELECTABLE_PAYMENT_TYPES = [
  PAYMENT_TYPE.CASH,
  PAYMENT_TYPE.RAZORPAY,
  PAYMENT_TYPE.CARD,
  PAYMENT_TYPE.UPI
];
